title: UhhhGoblin's Portfolio
logo: "meep.jpg" 
description: > 

  My name is Benicio aka UhhhGoblin and this is my Portfolio displaying my achievements in my Prog 101 semester. I begun these projects a couple months ago and learned a lot in my short time learning Programming. It's a lot of fun and can't wait to further impress myself as time goes on!
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
google_analytics: UA-000000-0
