title: UhhhGoblin
logo: "meep.jpg" 
description: > 

  My name is Benicio aka UhhhGoblin and this is my Portfolio displaying my achievements in my Prog 101 semester
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:


git commit --allow-empty -m "Trigger rebuild"
git push
